# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

real_to_pos <- function(x) {
    .Call('_sparseRGPs_real_to_pos', PACKAGE = 'sparseRGPs', x)
}

pos_to_real <- function(x) {
    .Call('_sparseRGPs_pos_to_real', PACKAGE = 'sparseRGPs', x)
}

real_to_bounded <- function(x, ub, lb) {
    .Call('_sparseRGPs_real_to_bounded', PACKAGE = 'sparseRGPs', x, ub, lb)
}

dsqexp_dsigmaC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_dsqexp_dsigmaC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

dsqexp_dsigma_ardC <- function(x1, x2, cov_par, lnames) {
    .Call('_sparseRGPs_dsqexp_dsigma_ardC', PACKAGE = 'sparseRGPs', x1, x2, cov_par, lnames)
}

dsqexp_dlC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_dsqexp_dlC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

dsqexp_dl_ardC <- function(x1, x2, cov_par, lnames, comp) {
    .Call('_sparseRGPs_dsqexp_dl_ardC', PACKAGE = 'sparseRGPs', x1, x2, cov_par, lnames, comp)
}

dsqexp_dtauC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_dsqexp_dtauC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

dsqexp_dx2C <- function(x1, x2, cov_par, lb, ub) {
    .Call('_sparseRGPs_dsqexp_dx2C', PACKAGE = 'sparseRGPs', x1, x2, cov_par, lb, ub)
}

dsqexp_dx2_ardC <- function(x1, x2, cov_par, lb, ub, lnames) {
    .Call('_sparseRGPs_dsqexp_dx2_ardC', PACKAGE = 'sparseRGPs', x1, x2, cov_par, lb, ub, lnames)
}

dexp_dsigmaC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_dexp_dsigmaC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

dexp_dlC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_dexp_dlC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

dexp_dtauC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_dexp_dtauC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

dsig_dthetaC <- function(x, x_pred, cov_par, cov_fun, par_name) {
    .Call('_sparseRGPs_dsig_dthetaC', PACKAGE = 'sparseRGPs', x, x_pred, cov_par, cov_fun, par_name)
}

dsig_dtheta_ardC <- function(x, x_pred, cov_par, cov_fun, par_name, lnames) {
    .Call('_sparseRGPs_dsig_dtheta_ardC', PACKAGE = 'sparseRGPs', x, x_pred, cov_par, cov_fun, par_name, lnames)
}

cov_fun_sqrd_expC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_cov_fun_sqrd_expC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

cov_fun_sqrd_exp_ardC <- function(x1, x2, cov_par, lnames) {
    .Call('_sparseRGPs_cov_fun_sqrd_exp_ardC', PACKAGE = 'sparseRGPs', x1, x2, cov_par, lnames)
}

cov_fun_expC <- function(x1, x2, cov_par) {
    .Call('_sparseRGPs_cov_fun_expC', PACKAGE = 'sparseRGPs', x1, x2, cov_par)
}

#' Make a covariance matrix with  covariance function
#'
#' @param x Matrix of observed data values
#' @param x_pred Potentially an empty matrix. If not empty, this returns
#' the covariance between x and x_pred.
#' @param cov_par Named list of covariance parameters. Need
#' "sigma", "tau", and "l1", ..., "ld" where d is the input dimension
#' @param cov_fun A character string specifying the covariance function.
#' Currently only works with "sqexp".
#' @param delta Scalar value that functions as a fixed nugget used to
#' stabilize matrix inverses and decompositions.
#' @return Covariance matrix at the observed data locations if
#' x_pred = matrix(), or the covariances between x and x_pred if
#' x_pred is not an empty matrix.
#' @export
make_cov_matC <- function(x, x_pred, cov_par, cov_fun, delta) {
    .Call('_sparseRGPs_make_cov_matC', PACKAGE = 'sparseRGPs', x, x_pred, cov_par, cov_fun, delta)
}

#' Make a covariance matrix with  covariance function
#'
#' @param x Matrix of observed data values
#' @param x_pred Potentially an empty matrix. If not empty, this returns
#' the covariance between x and x_pred.
#' @param cov_par Named list of covariance parameters. Need
#' "sigma", "tau", and "l1", ..., "ld" where d is the input dimension
#' @param cov_fun A character string specifying the covariance function.
#' Currently only works with "ard".
#' @param delta Scalar value that functions as a fixed nugget used to
#' stabilize matrix inverses and decompositions.
#' @param lnames Vector of the names of the length scale parameters, i.e.
#' "l1", ..., "ld"
#' @return Covariance matrix at the observed data locations if
#' x_pred = matrix(), or the covariances between x and x_pred if
#' x_pred is not an empty matrix.
#' @export
make_cov_mat_ardC <- function(x, x_pred, cov_par, cov_fun, delta, lnames) {
    .Call('_sparseRGPs_make_cov_mat_ardC', PACKAGE = 'sparseRGPs', x, x_pred, cov_par, cov_fun, delta, lnames)
}

